name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: asdf-vm/actions/install@v2.2.0
      - run: asdf plugin add nodejs .
      - run: asdf list-all nodejs
      - run: asdf install nodejs latest
      - run: asdf global nodejs latest
      - run: type node
      - run: node --help

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: asdf-vm/actions/install@v2.2.0
      - run: asdf install
      - run: make lint-check
